# Numpy
* Fixed Type
* Contiguous Memory


In [ ]:
import numpy as np

# The Basics

In [ ]:
a = np.array([1, 2, 3], dtype=np.int8)
b = np.array([[9, 8, 7, 11, 24], [6, 5, 4, 45, 67], [3, 2, 1, 16, 12]], dtype=np.float64)
a, b

(array([1, 2, 3], dtype=int8),
 array([[ 9.,  8.,  7., 11., 24.],
        [ 6.,  5.,  4., 45., 67.],
        [ 3.,  2.,  1., 16., 12.]]))

In [ ]:
# Get dimensions
a.ndim, b.ndim

(1, 2)

In [ ]:
# Get shape
a.shape, b.shape

((3,), (3, 5))

In [ ]:
# Get type
a.dtype, b.dtype

(dtype('int8'), dtype('float64'))

In [ ]:
# Each item size
a.itemsize, b.itemsize # each item size in Byte

(1, 8)

In [ ]:
# Total size
# nbytes = size * itemsize
a.nbytes, b.nbytes

(3, 120)

In [ ]:
# b[i, j] i=row, j=col
# Get specific row
b[1, :]

array([ 6.,  5.,  4., 45., 67.])

In [ ]:
# Get even indexes started from index 2
b[:, 2::2] = 78

In [ ]:
# b[0, :] = 78
b[0, :] = [1, 2, 3, 4, 5] # List should be the same size and dimensions
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  5., 78., 45., 78.],
       [ 3.,  2., 78., 16., 78.]])

# 3D example

In [ ]:
c = np.zeros(shape=(2, 3, 4), dtype=np.float16)
c[0, 1, :] = [1, 2, 3, 4]
c

array([[[0., 0., 0., 0.],
        [1., 2., 3., 4.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float16)

In [ ]:
# outside in
c[0, 1, 3]

np.float16(4.0)

# Initialize different types of arrays

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2, 3), dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [ ]:
np.full(shape=(2, 3), fill_value=123)

array([[123, 123, 123],
       [123, 123, 123]])

In [ ]:
np.full_like(a, 12)

array([12, 12, 12], dtype=int8)

# Random

In [ ]:
# Random int
np.random.randint(low=0, high=12, size=(3, 4))

array([[ 2, 10,  3, 11],
       [ 0,  8,  7, 11],
       [ 8,  6,  7,  2]])

In [ ]:
# Random 0-1 just pass size to it
np.random.rand(3, 2)

array([[0.95567647, 0.6325864 ],
       [0.7441816 , 0.50506503],
       [0.41507009, 0.04014501]])

In [ ]:
# Random 0-1 just pass size to it
np.random.random_sample(size=b.shape)

array([[0.65321004, 0.93401116, 0.239411  , 0.1699394 , 0.15857918],
       [0.49180305, 0.47913441, 0.67379083, 0.0516425 , 0.68931425],
       [0.78729527, 0.07978258, 0.71997382, 0.55340929, 0.1960921 ]])

In [ ]:
# Identity matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
array = np.array([2, 4, 6])
np.repeat(array, 3)

array([2, 2, 2, 4, 4, 4, 6, 6, 6])

In [ ]:
array = np.array([[2, 4, 6]])
np.repeat(array, 3, axis=0)

array([[2, 4, 6],
       [2, 4, 6],
       [2, 4, 6]])

# Exercise

In [ ]:
# Create a zeros array that edges=1 and center=9
# Way 1
array = np.zeros(shape=(11, 11), dtype=np.int8)
r_l, c_l = array.shape

array[r_l // 2, c_l // 2] = 9

array[0::r_l - 1, :] = 1
array[:, 0::c_l - 1] = 1

array

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 9, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)

In [ ]:
# Way 2
array = np.ones(shape=(11, 11), dtype=np.int8)
r_l, c_l = array.shape

z = np.zeros(shape=(r_l - 2, c_l -2))
z[(r_l - 2) // 2, (c_l - 2) // 2] = 9

array[1:-1, 1:-1] = z

array

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 9, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)

# Mathematics

In [ ]:
a = np.array([1, 2, 3, 4])
a + 2 # * ** + - / // etc


array([1, 2, 3, 4])

In [ ]:
b = np.array([2, 4, 9, 8]),
a + b # * ** +,,   - / // etc

array([[ 3,  6, 12, 12]])

In [ ]:
np.sin(b)

array([[ 0.90929743, -0.7568025 ,  0.41211849,  0.98935825]])

# Linear Algebra

In [ ]:
mat_a = np.random.randint(1, 5, (3, 4))
mat_b = np.random.randint(1, 5, (4, 2))

mat_a, mat_b

(array([[2, 2, 2, 2],
        [4, 4, 2, 1],
        [4, 3, 4, 2]]),
 array([[2, 1],
        [4, 1],
        [3, 3],
        [4, 2]]))

In [ ]:
# mat_a@mat_b
np.matmul(mat_a, mat_b)

array([[26, 14],
       [34, 16],
       [40, 23]])

In [ ]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

# Statistics

In [ ]:
stats = np.array([[1,2,3], [4, 5, 6]])

In [ ]:
np.min(stats, axis=0) # each cols

array([1, 2, 3])

In [ ]:
np.max(stats, axis=1) # each rows

array([3, 6])

In [ ]:
np.mean(stats)

np.float64(3.5)

In [ ]:
np.sum(stats)

np.int64(21)

# Reorganizing Arrays

In [ ]:
stats.reshape((-1,))

array([1, 2, 3, 4, 5, 6])

# Vertical & Horizontal stacks

In [ ]:
a = stats.reshape((3, 2))
b = np.random.randint(1, 5, (3, 2))

In [ ]:
np.hstack([a, b])

array([[1, 2, 4, 4],
       [3, 4, 3, 3],
       [5, 6, 3, 3]])

In [ ]:
np.vstack([a, b])

array([[1, 2],
       [3, 4],
       [5, 6],
       [4, 4],
       [3, 3],
       [3, 3]])

# Load Data

In [ ]:
# np.genfromtxt("file.txt", delimiter=",")

# Boolean Masking and Advanced Indexing

In [ ]:
data = np.random.randint(1, 500, (5, 4))

In [ ]:
data[data > 100] # return values that match with condition

array([469, 396, 484, 155, 310, 265, 416, 337, 240, 135, 353, 482, 201])

In [ ]:
# data > 100
((data > 100) & (data < 200))
# ~((data > 100) & (data < 200)) # not

array([[ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True]])

In [ ]:
np.any(data > 469, axis=0) # col

array([False,  True, False,  True])

# Index with list


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1, 2, 8]]

array([2, 3, 9])